name: Release on Merge to Main

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ 1.25.x ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Run tests with coverage
        run: make test-coverage
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed for tagging and changelog

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.work

      - name: Install AWS multi-module tools
        run: |
          go install github.com/awslabs/aws-go-multi-module-repository-tools/cmd/calculaterelease@latest
          go install github.com/awslabs/aws-go-multi-module-repository-tools/cmd/tagrelease@latest
          go install github.com/awslabs/aws-go-multi-module-repository-tools/cmd/generatechangelog@latest
          go install github.com/awslabs/aws-go-multi-module-repository-tools/cmd/changelog@latest
          go install github.com/awslabs/aws-go-multi-module-repository-tools/cmd/updatemodulemeta@latest

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Calculate next per-module versions
        run: |
          rm -f release.json
          calculaterelease -o release.json

      - name: Create and push tags per module
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tagrelease -release release.json
          # Ensure tags are pushed if created locally
          git push --follow-tags || true

      - name: Update module metadata
        run: |
          if command -v updatemodulemeta >/dev/null 2>&1; then
            updatemodulemeta -release release.json || true
          else
            echo "updatemodulemeta not available; skipping"
          fi

      - name: Generate changelog
        run: |
          # Generate changelog from calculated release manifest
          if command -v generatechangelog >/dev/null 2>&1; then
            generatechangelog -release release.json -o CHANGELOG.md || echo "generatechangelog failed; skipping changelog generation"
          else
            echo "generatechangelog not available; skipping changelog generation"
          fi

      - name: Commit and push changelog/metadata changes (if any)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "chore(release): update changelog and module metadata [skip ci]"
            git push origin HEAD:main
          else
            echo "No changes to commit."
          fi
